baseURL = 'https://annamarstad.se/'
languageCode = 'en-us'
title = 'Anna Mårstad – samtal och handledning'
themesDir = "themes"
theme = "hugo-hero-theme"

[[menu.main]]
  name = "Hem"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tjänster"
  url = "/services/"
  weight = 2

[[menu.main]]
  name = "Kontakt"
  url = "/contact/"
  weight = 3


